# Generated by Django 5.0.3 on 2024-03-26 21:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(max_length=250)),
                ('interval_short_name', models.CharField(max_length=20)),
                ('frets_from_root', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=2)),
                ('note_enharmonic', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ChordInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretter.chord')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretter.interval')),
            ],
            options={
                'unique_together': {('chord', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='ScaleInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretter.interval')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretter.scale')),
            ],
            options={
                'unique_together': {('scale', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='TuningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_number', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('tuning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretter.tuning')),
            ],
            options={
                'unique_together': {('tuning', 'string_number')},
            },
        ),
    ]
