# Generated by Django 5.0.3 on 2024-03-26 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuningnote',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fretter.note'),
            preserve_default=False,
        ),
    ]
