# Generated by Django 5.0.3 on 2024-03-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fretter', '0002_tuningnote_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chord',
            old_name='chord_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='interval_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='interval_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_enharmonic',
            new_name='enharmonic',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='scale_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tuning',
            old_name='tuning_name',
            new_name='name',
        ),
    ]
